### ISSUE TITLE
Can't init library

### ISSUE THREAD

**Issue by mikikg** [Kochchri/node-mcp23s17#1]
Hi,

first at all I would like to thank you for such useful library, great work.

At a moment I can't make this running, I get following error:

```
/root/mcp23s17/proba/node_modules/mcp23s17/index.js:202
		cb( result );
		^
TypeError: undefined is not a function
    at /root/mcp23s17/proba/node_modules/mcp23s17/index.js:202:3
    at Spi.transfer (/root/mcp23s17/proba/node_modules/mcp23s17/node_modules/spi/spi.js:88:29)
    at MCP23S17.read (/root/mcp23s17/proba/node_modules/mcp23s17/index.js:200:11)
    at null.<anonymous> (/root/mcp23s17/proba/proba.js:33:15)
    at wrapper [as _onTimeout] (timers.js:274:14)
    at Timer.listOnTimeout (timers.js:119:15)
```

I'm using stock version of Node.JS v0.12.6 which comes with Raspbian.

Also, not related to your library, for some reason I can't use binary representations of numbers like "0b1000000", I get SyntaxError?!

What is wrong here, does I need some other Node.JS version?

Thanks in advance.

BTW: I got working expander with WiringPi library (C/C++), so HW side is ok.
http://wiringpi.com/extensions/spi-mcp23s08-mcp23s17/

**Comment by Kochchri** [comment]
Hi mikikg, thanks for using my library ;)

the error you get is just because you read something without giving the function a callback pointer.

I think you use the read command like that right?
`read( pin );`

You should at least give a empty callback function
`read( pin, function(){});`

But for best performance alway use the callback.

**Comment by mikikg** [comment]
Hi, tnx for quick repply.

My test code is simple as this (there I got error shown in first post):

```
// load the library 
MCPLib = require('mcp23s17');
 
// create new instance width device and chip_adress 
// needed default settings are set (more options will follow) 
mcp_1 = new MCPLib.MCP23S17( '/dev/spidev0.0', 0 );
 
// connect decive 
mcp_1.connect();
 
//var status = 0b10000000;
var status = 128;

setInterval( function(){
        
        /*
        if( status == 0b00000000 ){
                status = 0b10000000;
        } else {
                status = 0b00000000;
        }
        */
        
        if( status == 0 ){
                status = 128;
        } else {
                status = 0;
        }
                
        mcp_1.write( 'B', status );
        mcp_1.read( 'B', function( s ){
                console.log( s );
        });
}, 500);

```

**Comment by Kochchri** [comment]
ok, so this is an example for an older version of this library. Please check out the new one.

**Comment by mikikg** [comment]
Yeah, It was old example.
I used now new one and it WORKS!

Sorry to bother you, but at least I'm confirming that this library works!

Many tnx!
